### ISSUE TITLE
Add a layout problem type which refuses negative widths and/or heights.

### ISSUE THREAD

**Issue by cryptoquick** [yoga-framework/yoga#57]

**Comment by cryptoquick** [comment]
How should we do this if there are additional constraints that apply when the width/height are positive?

**Comment by morganthomas** [comment]
We can accomplish this using piecewise objective functions.

**Comment by morganthomas** [comment]
Using piecewise objective functions proves to be complex. I think a better approach is to add a penalty on whatever dimension is supposed to be constrained by just adding a half-parabola dependent on that dimension to the objective function.

**Comment by morganthomas** [comment]
Well, I guess that half-parabolas are a kind of piecewise objective function.

**Comment by morganthomas** [comment]
There's an example in boxes_2, but it doesn't quite work the way one would want (check it out). Further refinements are necessary.

**Comment by morganthomas** [comment]
This issue is solved, intrinsically speaking; the issue we're seeing will be solved by #60, but the issue is a lack of feature rather than a bug, since there's nothing intrinsically incorrect about the only currently possible behavior.
